const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const file = path.join(root, 'index.html');
let html = fs.readFileSync(file, 'utf8');
const main = fs.readFileSync(path.join(__dirname, 'home-template.html'), 'utf8').trim();
if (!/<main\b[\s\S]*?<\/main>/.test(html)) throw new Error('Homepage main not found');
html = html.replace(/<main\b[\s\S]*?<\/main>/, main);
html = html.replace(/<link\b[^>]*rel=["']canonical["'][^>]*>\s*/gi, '');
html = html.replace(/<link\b[^>]*(?:wp-json|EditURI|shortlink)[^>]*>\s*/gi, '');
html = html.replace(/<meta\b[^>]*name=["']generator["'][^>]*>\s*/gi, '');
html = html.replace(/<link[^>]*href="\/assets\/home.css"[^>]*>\s*/g, '').replace(/<script[^>]*src="\/assets\/home.js"[^>]*><\/script>\s*/g, '');
html = html.replace('</head>', '<link rel="canonical" href="https://4050guide.co.kr/">\n<link rel="stylesheet" href="/assets/home.css">\n<script src="/assets/home.js" defer></script>\n</head>');
html = html.replace(/<title>[\s\S]*?<\/title>/, '<title>4050가이드 - 퇴직 후 생활비와 재취업 준비</title>');
html = html.replace(/(<meta name="description" content=")[^"]*(")/, '$140대·50대를 위한 퇴직 후 건강보험료, 재취업 상담, 국비훈련, 부모님 복지 안내. 내 상황에서 먼저 확인할 순서와 공식 출처를 살펴보세요.$2');
html = html.replace(/(<meta (?:property="og:title"|name="twitter:title") content=")[^"]*(")/g, '$14050가이드 - 퇴직 후 생활비와 재취업 준비$2');
html = html.replace(/(<meta (?:property="og:description"|name="twitter:description") content=")[^"]*(")/g, '$1퇴직 직후, 재취업 준비, 부모님 복지, 생활비 부담. 내 상황에서 먼저 확인할 순서와 공식 출처를 살펴보세요.$2');
fs.writeFileSync(file, html);
console.log('Built situation-based homepage');
